install-air:
	go install github.com/air-verse/air@latest

# Run simulations
simulate:
	air -- --simulate

# Play the game in the terminal
play-terminal:
	go run . --play-terminal

# Print all bets for a given number
bets:
	go run . --bets

# Run the robot
run-robot:
	go run . --robot

# Build the roulette map
build-map:
	go run . --build-map

# Play the game with the robot
play-robot:
	go run . --play-robot

# Print the mouse position
mouse-position:
	go run . --mouse-position
