install-air:
	go install github.com/air-verse/air@latest

# Run simulations
simulate:
	air -- --simulate

# Play the game in the terminal
play-terminal:
	go run . --play-terminal

# Print all bets for a given number
bets:
	go run . --bets
